// Simple API Explorer Backend
// Serves APIs from the registry generated by the Python pipeline

const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());
app.use(express.json());

// Path to the registry file
const REGISTRY_PATH = path.join(__dirname, '..', 'registry', 'apis.json');

/**
 * Load APIs from the registry file
 */
function loadAPIs() {
  try {
    if (fs.existsSync(REGISTRY_PATH)) {
      const data = fs.readFileSync(REGISTRY_PATH, 'utf8');
      return JSON.parse(data);
    }
    return [];
  } catch (error) {
    console.error('Error loading APIs:', error.message);
    return [];
  }
}

/**
 * GET /apis
 * Returns all APIs from the registry
 */
app.get('/apis', (req, res) => {
  try {
    const apis = loadAPIs();
    
    res.json({
      success: true,
      count: apis.length,
      apis: apis,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: 'Failed to load APIs',
      message: error.message
    });
  }
});

/**
 * GET /apis/:id
 * Returns a specific API by index
 */
app.get('/apis/:id', (req, res) => {
  try {
    const apis = loadAPIs();
    const id = parseInt(req.params.id);
    
    if (isNaN(id) || id < 0 || id >= apis.length) {
      return res.status(404).json({
        success: false,
        error: 'API not found',
        message: `No API found at index ${req.params.id}`
      });
    }
    
    res.json({
      success: true,
      api: apis[id],
      index: id,
      timestamp: new Date().toISOString()
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      error: 'Failed to load API',
      message: error.message
    });
  }
});

/**
 * GET /health
 * Health check endpoint
 */
app.get('/health', (req, res) => {
  const apis = loadAPIs();
  
  res.json({
    success: true,
    status: 'healthy',
    registryPath: REGISTRY_PATH,
    registryExists: fs.existsSync(REGISTRY_PATH),
    apiCount: apis.length,
    uptime: process.uptime(),
    timestamp: new Date().toISOString()
  });
});

/**
 * GET /
 * Root endpoint with documentation
 */
app.get('/', (req, res) => {
  const apis = loadAPIs();
  
  res.json({
    message: 'Niharika\'s API Explorer Backend',
    description: 'Simple backend serving APIs from Python pipeline registry',
    author: 'Niharika Jakkula',
    project: 'GSoC 2026 PoC',
    endpoints: {
      'GET /apis': 'Get all APIs from registry',
      'GET /apis/:id': 'Get API by index',
      'GET /health': 'Health check',
      'GET /': 'This documentation'
    },
    stats: {
      totalAPIs: apis.length,
      registryPath: REGISTRY_PATH
    },
    timestamp: new Date().toISOString()
  });
});

// 404 handler
app.use('*', (req, res) => {
  res.status(404).json({
    success: false,
    error: 'Endpoint not found',
    message: `${req.method} ${req.originalUrl} does not exist`,
    availableEndpoints: ['/apis', '/apis/:id', '/health', '/']
  });
});

// Start server
app.listen(PORT, () => {
  const apis = loadAPIs();
  
  console.log('🚀 ================================');
  console.log('🚀 Niharika\'s API Explorer Backend');
  console.log('🚀 ================================');
  console.log(`🚀 Server running on port ${PORT}`);
  console.log(`🚀 Server URL: http://localhost:${PORT}`);
  console.log(`🚀 Registry: ${REGISTRY_PATH}`);
  console.log(`🚀 APIs loaded: ${apis.length}`);
  console.log('🚀 ================================');
  console.log('🚀 Endpoints:');
  console.log('🚀   GET /apis       - List all APIs');
  console.log('🚀   GET /apis/:id   - Get API by index');
  console.log('🚀   GET /health     - Health check');
  console.log('🚀 ================================');
});

module.exports = app;